import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  en: {
    plato: "Plato",

    // Navigation & General
    welcome: "Welcome to Plato!",
    buildProfile: "Build Your Complete Profile",
    takeInterview: "Take AI Interview",
    getStarted: "Get Started with Plato",
    complete: "Complete",
    startInterview: "Start Interview",
    buildProfileButton: "Build Profile",
    
    // Profile Section
    profileDescription: "Build your professional profile including personal details, education, work experience, skills, and career preferences. Reach 85% to unlock interviews.",
    interviewDescription: "Build your profile to 85% completion to unlock the AI interview.",
    
    // Steps
    step1: "Build your complete profile including personal details, education, work experience, skills, and career preferences.",
    step2: "Complete your AI interview to generate your comprehensive professional analysis.",
    
    // Common buttons
    save: "Save",
    cancel: "Cancel",
    continue: "Continue",
    next: "Next",
    previous: "Previous",
    close: "Close",
    signOut: "Sign Out",
    signingOut: "Signing Out...",
    
    // Interview specific
    selectLanguage: "Select Interview Language",
    interviewLanguagePrompt: "Which language would you like to take the interview in?",
    english: "English",
    arabic: "العربية",
    proceedInEnglish: "Proceed in English",
    proceedInArabic: "Proceed in Arabic",
    chooseStyle: "Choose Your Interview Style",
    selectExperience: "Interview - Select how you'd like to experience your AI interview",
    languageNote: "The AI interviewer will ask questions and expect responses in your selected language",
    
    // Profile completion
    profileProgress: "Profile progress saved!",
    profileComplete: "Your profile is {{percentage}}% complete. {{status}}",
    interviewsUnlocked: "Great! Your profile is ready for interviews (75%+ complete).",
    continueBuilding: "Continue building to unlock interviews at 75%.",
    
    // Dashboard
    jobDashboard: "Your Job Dashboard",
    
    // Dashboard sections
    jobMatches: "Job Matches",
    applications: "Applications", 
    upcomingInterviews: "Upcoming Interviews",
    jobPostings: "Job Postings",
    
    // Dashboard content
    aiCuratedOpportunities: "AI-Curated Opportunities",
    discoverPersonalizedJobs: "Discover personalized job matches based on your AI interview analysis and profile data",
    trackApplicationProgress: "Track Application Progress",
    monitorApplicationStatus: "Monitor your job applications and interview schedules across all platforms",
    exploreOpportunities: "Explore New Opportunities",
    browseLatestJobs: "Browse the latest job openings that match your skills and career goals",
    viewUpcomingSchedule: "View Your Upcoming Schedule",
    stayUpdated: "Stay updated with your confirmed interviews and important dates",
    
    // Stats and labels
    responseRate: "response rate",
    applicationResponseRate: "application response rate",
    whyJobSeekingChallenging: "Why Job Seeking Is So Challenging",
    
    // Common actions
    viewAll: "View All",
    noDataAvailable: "No data available",
    loadingData: "Loading data...",
    
    // Applications section
    myApplications: "My Applications",
    trackApplicationStatus: "Track your application status and progress",
    
    // Quick stats
    quickStats: "Quick Stats",
    jobMatchesLabel: "Job Matches",
    applicationsLabel: "Applications",
    profileCompletionLabel: "Profile Completion",
    
    // Industry challenge stats
    avgJobSearchTime: "average job search time",
    applicationsToGetOffer: "applications to get one offer",
    sixMonths: "6 months",
    oneHundredEighteen: "118",
    twoPercent: "2%",
    
    // Forms
    personalDetails: "Personal",
    workExperience: "Experience",
    education: "Education",
    skills: "Skills",
    jobTarget: "Target",
    
    // Language switch
    switchLanguage: "العربية",
    
    // Landing page
    landing: {
      hero: {
        title: "Get Your Dream Job with Precision AI Matching",
        subtitle: "Navigate your career journey with intelligent job discovery and AI-powered profile analysis that reveals your true potential.",
        getStarted: "Start Now",
        learnMore: "Learn More"
      },
      features: {
        aiPoweredMatching: "AI-Powered Matching",
        smartInterviews: "Smart Interviews", 
        instantResults: "Instant Results",
        aiInterview: {
          title: "AI Interview",
          description: "Have a natural conversation with our AI to build your professional profile automatically"
        },
        smartMatching: {
          title: "Smart Matching",
          description: "Get matched to jobs with precision scoring based on your skills, experience, and goals"
        },
        instantResultsFeature: {
          title: "Instant Results",
          description: "See your matches immediately with detailed scoring and application tracking"
        }
      },
      companies: {
        title: "Trusted by Leading Companies",
        subtitle: "Join thousands of professionals who have found their perfect career match through our AI-powered platform",
        testimonial: "Revolutionary approach to talent acquisition",
        subtitle2: "Join the companies shaping the future of hiring"
      },
      cta: {
        title: "Ready to find your perfect job match?",
        subtitle: "Join thousands of professionals who've discovered their dream careers with AI-powered job matching",
        startJourney: "Start Your Journey"
      }
    },
    
    // Auth
    auth: {
      signIn: "Sign In",
      signUp: "Sign Up", 
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      firstName: "First Name",
      lastName: "Last Name",
      username: "Username",
      enterEmail: "Enter your email",
      enterPassword: "Enter your password",
      confirmYourPassword: "Confirm your password",
      firstNamePlaceholder: "First name",
      lastNamePlaceholder: "Last name",
      usernamePlaceholder: "Username",
      usernameOptional: "Username (Optional)",
      chooseUsername: "Choose a username",
      createPassword: "Create a password",
      signingIn: "Signing In...",
      signingUp: "Signing Up...",
      createAccount: "Create Account",
      invalidEmail: "Invalid email address",
      passwordRequired: "Password is required",
      passwordMinLength: "Password must be at least 6 characters",
      firstNameRequired: "First name is required",
      lastNameRequired: "Last name is required",
      usernameMinLength: "Username must be at least 3 characters",
      passwordsDontMatch: "Passwords don't match",
      welcomeToPlato: "Welcome to Plato"
    },
    
    // Interview Modal
    interview: {
      chooseStyle: "Choose Interview Style",
      selectExperience: "Select Interview Type",
      selectLanguage: "Select Interview Language",
      languageNote: "The AI interviewer will ask questions and expect responses in the language you select",
      // Error messages
      voiceInterviewError: "Voice Interview Error",
      voiceInterviewErrorDescription: "There was an issue with the voice interview. Please try text mode instead.",
      unauthorized: "Unauthorized",
      loggingOut: "You are logged out. Logging in again...",
      startError: "Error",
      startErrorDescription: "Failed to start interview. Please try again.",
      allInterviewsComplete: "All Interviews Complete!",
      profileGeneratedSuccessfully: "Your comprehensive AI profile has been generated successfully.",
      interviewSectionComplete: "Interview Section Complete",
      movingTo: "Moving to",
      interview: "interview",
      continueRemainingInterviews: "Continue with the remaining interviews to complete your profile.",
      processResponseError: "Error",
      processResponseErrorDescription: "Failed to process your response",
      submissionFailed: "Submission Failed",
      submissionFailedDescription: "There was an issue submitting your interview. Please try again.",
      voiceInterviewComplete: "Interview Complete!",
      voiceInterviewProcessedSuccessfully: "Your voice interview has been processed successfully.",
      processingFailed: "Processing Failed",
      processingFailedDescription: "There was an issue processing your interview",
      processAnswerError: "Error",
      processAnswerErrorDescription: "Failed to process your answer. Please try again.",
      completeInterviewError: "Error",
      completeInterviewErrorDescription: "Failed to complete interview. Please try again.",
      selectInterviewTypeError: "Error",
      selectInterviewTypeErrorDescription: "Please select an interview type first.",
      startingVoiceInterviewConnecting: "Starting your voice interview... Connecting to AI interviewer...",
      voiceInterviewStarted: "Voice Interview Started",
      voiceInterviewStartedDescription: "You can now speak naturally with the AI interviewer.",
      connectionFailed: "Connection Failed",
      couldNotStartVoiceInterview: "Could not start voice interview",
      tryTextMode: "Please try text mode",
      startingTextInterview: "Starting your text interview... Please wait while I prepare your personalized questions.",
      questionContentNotAvailable: "Question content not available",
      textInterviewStarted: "Text Interview Started",
      textInterviewStartedDescription: "You can now type your responses to the interview questions.",
      failedToStartInterview: "Failed to Start Interview",
      couldNotStartTextInterview: "Could not start text interview",
      pleaseTryAgain: "Please try again",
      question1: "Question 1",
      interviewInProgress: "Interview in Progress",
      waitBeforeClosing: "Please wait for the current interaction to complete before closing.",
      chooseYourInterview: "Choose Your Interview",
      completeAllInterviews: "Complete all 3 interviews in order to generate your comprehensive AI profile",
      interviewOrder: "Interviews must be completed in this order: Personal → Professional → Technical",
      locked: "(Locked)",
      completePreviousInterviews: "Complete previous interviews first",
      completed: "Completed",
      start: "Start",
      backToInterviewTypes: "Back to Interview Types",
      preparingInterviewQuestions: "Preparing interview questions...",
      typeResponsesAtOwnPace: "Type your responses at your own pace",
      textInterview: "Text Interview",
      preparingQuestions: "Preparing questions...",
      processingYourResponse: "Processing your response...",
      interviewComplete: "Interview Complete!",
      interviewSectionCompletedSuccessfully: "Interview section completed successfully! Continue with remaining interviews to complete your profile.",
      typeYourAnswerHere: "Type your answer here...",
      submitting: "Submitting...",
      submitInterview: "Submit Interview",
      processing: "Processing...",
      submitAnswer: "Submit Answer",
      live: "Live",
      startingInterview: "Starting Interview...",
      aiIsSpeaking: "AI is Speaking...",
      aiInterviewActive: "AI Interview Active",
      connecting: "Connecting...",
      preparingYourPersonalizedQuestions: "Preparing your personalized questions...",
      waitForAiToFinishSpeaking: "Please wait for the AI to finish speaking before responding",
      aiWillGuideYou: "the AI will guide you through",
      questions: "questions",
      settingUpVoiceInterview: "Setting up your voice interview...",
      aiInterviewer: "AI Interviewer",
      you: "You",
      processingInterview: "Processing Interview...",
      hangUp: "Hang Up",
      aiInterview: "AI Interview",
      success: "Success",
      resumeUploadedSuccessfully: "Resume uploaded successfully! You can now start interviews."
    },
    
    // Interview Types
    voiceInterview: "Voice Interview",
    textInterview: "Text Interview",
    startingVoiceInterview: "Starting voice interview...",
    speakNaturally: "Speak naturally with the AI interviewer",
    
    // Interview type descriptions
    personalInterview: "Personal Interview",
    personalInterviewDescription: "Understanding your personal self, background, and history",
    professionalInterview: "Professional Interview",
    professionalInterviewDescription: "Exploring your career background and professional experience",
    technicalInterview: "Technical Interview",
    technicalInterviewDescription: "Dynamic assessment based on your field - problem solving and IQ evaluation",
    
    // Languages
    languages: {
      english: "English",
      arabic: "العربية"
    },
    
    // Dashboard
    dashboard: {
      invalidFileType: "Invalid File Type",
      invalidFileTypeDescription: "Please upload a PDF or text file.",
      pdfUploadTips: "PDF Upload Tips",
      pdfUploadTipsDescription: "PDF uploaded! For guaranteed auto-population, also try uploading a text (.txt) version of your resume if the PDF extraction doesn't work well.",
      fileTooLarge: "File Too Large",
      fileTooLargeDescription: "Please upload a file smaller than 10MB.",
      resumeProcessedSuccessfully: "Resume Processed Successfully! 🎉",
      resumeProcessedDescription: "Profile auto-populated with {{sections}} sections from your resume.",
      uploadFailed: "Upload Failed",
      uploadFailedDescription: "Failed to process resume. Please try again.",
      editingProfile: "Editing Profile...",
      readyToFindRole: "Ready to Find Your Perfect Role! 🎉",
      readyToFindRoleDescription: "Your profile is complete and your AI interview has generated a comprehensive professional analysis. Use the tools below to discover opportunities that match your unique skills and career goals.",
      completeSteps: "Complete both steps below to unlock personalized job matching and access your full dashboard:",
      uploadResume: "Upload Resume",
      uploading: "Uploading...",
      editProfile: "Edit Profile",
      excellentInterviewComplete: "Excellent! Your AI interview is complete.",
      reviewInterview: "Review Interview",
      jobSpecificAI: "Job specific AI interviews",
      jobSpecificAIDescription: "See job invites tailored for you and practice",
      invitedJobs: "Invited Jobs",
      invitedJobsDescription: "View jobs you're invited to and apply",
      browseJobPostings: "Browse Job Postings",
      getStartedWithPlato: "Get Started with Plato",
      getStartedWithPlatoDescription: "Complete both steps above to unlock your personalized job dashboard with matches, applications, and career insights.",
      step1Description: "Step 1: Build your complete profile including personal details, education, work experience, skills, and career preferences.",
      step2Description: "Step 2: Complete your AI interview to generate your comprehensive professional analysis.",
      
      // Additional missing translations
      phone: "Phone",
      selectGender: "Select gender",
      selectCareerLevel: "Select career level",
      entryLevel: "Entry Level",
      junior: "Junior",
      midLevel: "Mid Level",
      senior: "Senior",
      lead: "Lead",
      manager: "Manager",
      director: "Director",
      executive: "Executive",
      selectType: "Select type",
      fullTime: "Full-time",
      partTime: "Part-time",
      contract: "Contract",
      freelance: "Freelance",
      internship: "Internship",
      selectAuthorizationStatus: "Select authorization status",
      citizen: "Citizen",
      permanentResident: "Permanent Resident",
      workVisa: "Work Visa",
      studentVisa: "Student Visa",
      selectPreference: "Select preference",
      onsite: "On-site",
      remote: "Remote",
      hybrid: "Hybrid",
      flexible: "Flexible",
      selectTravelWillingness: "Select travel willingness",
      none: "None",
      minimal: "Minimal",
      moderate: "Moderate",
      extensive: "Extensive",
      targetRoles: "Target Roles",
      targetIndustries: "Target Industries",
      targetCompanies: "Target Companies",
      salaryExpectations: "Salary Expectations",
      minimumSalary: "Minimum Salary",
      maximumSalary: "Maximum Salary",
      currency: "Currency",
      period: "Period",
      monthly: "Monthly",
      annually: "Annually",
      salaryIsNegotiable: "Salary is negotiable",
      careerGoals: "Career Goals",
      describeCareerGoalsAspirations: "Describe your career goals and aspirations",
      workStyle: "Work Style",
      describePreferredWorkStyle: "Describe your preferred work style",
      whatMotivatesYou: "What Motivates You",
      whatDrivesMotivatesCareer: "What drives and motivates you in your career?",
      dealBreakers: "Deal Breakers",
      dealBreakersJob: "What are your deal breakers in a job?",
      enterFirstName: "Enter first name",
      enterLastName: "Enter last name",
      enterEmail: "Enter email",
      enterPhone: "Enter phone number",
      dateOfBirth: "Date of Birth",
      gender: "Gender",
      nationality: "Nationality",
      enterNationality: "Enter nationality",
      address: "Address",
      streetAddress: "Street Address",
      enterStreetAddress: "Enter street address",
      city: "City",
      enterCity: "Enter city",
      stateProvince: "State/Province",
      enterStateProvince: "Enter state or province",
      country: "Country",
      enterCountry: "Enter country",
      postalCode: "Postal Code",
      enterPostalCode: "Enter postal code",
      emergencyContact: "Emergency Contact",
      emergencyContactName: "Emergency contact name",
      relationshipToYou: "Relationship to you",
      emergencyContactPhone: "Emergency contact phone",
      name: "Name",
      relationship: "Relationship",
      saving: "Saving...",
      lastSaved: "Last saved",
      errorSavingProfile: "Error saving profile",
      pleaseCheckFieldsTryAgain: "Please check all required fields and try again.",
      saveError: "Save Error",
      saveErrorDescription: "There was an error saving your progress. Please try again.",
      saveDraft: "Save Draft",
      saveProgress: "Save Progress",
      enterZero: "0",
      egyptianPound: "EGP",
      usDollar: "USD",
      euro: "EUR",
      britishPound: "GBP",
      saudiRiyal: "SAR",
      uaeDirham: "AED",
      male: "Male",
      female: "Female",
      nonBinary: "Non-binary",
      preferNotToSay: "Prefer not to say",
      other: "Other",
      validEmailRequired: "Valid email is required",
      validPhoneNumberRequired: "Valid phone number is required",
      hourly: "Hourly",
      hourlyPlaceholder: "e.g., 50",
      skills: {
        industryKnowledge: "Industry Knowledge",
        tools: "Tools",
        addIndustryKnowledge: "Add Industry Knowledge",
        addTools: "Add Tools",
        industryKnowledgePlaceholder: "e.g., Finance, Healthcare, Technology",
        toolsPlaceholder: "e.g., Figma, Adobe Creative Suite, Jira",
      },
      industryKnowledge: "Industry Knowledge",
      tools: "Tools",
      addIndustryKnowledge: "Add Industry Knowledge",
      addTools: "Add Tools",
      industryKnowledgePlaceholder: "e.g., Finance, Healthcare, Technology",
      toolsPlaceholder: "e.g., Figma, Adobe Creative Suite, Jira",
      thesis: "Thesis",
      thesisPlaceholder: "e.g., 'Machine Learning Applications in Healthcare'",
      technologies: "Technologies",
      technologiesPlaceholder: "e.g., React, Node.js, Python",
      teamSize: "Team Size",
      teamSizePlaceholder: "e.g., 5-10",
      reportingTo: "Reporting To",
      reportingToPlaceholder: "e.g., Engineering Manager",
      salary: "Salary",
      salaryAmount: "Salary Amount",
      salaryAmountPlaceholder: "e.g., 5000",
      benefits: "Benefits",
      healthInsurance: "Health Insurance",
      retirementPlan: "Retirement Plan",
      paidTimeOff: "Paid Time Off",
      flexibleSchedule: "Flexible Schedule",
      remoteWork: "Remote Work",
      professionalDevelopment: "Professional Development",
      stockOptions: "Stock Options",
      otherBenefits: "Other Benefits",
      addOtherBenefit: "Add Other Benefit",
      otherBenefitPlaceholder: "e.g., Company Car, Gym Membership",
    },
    
    // Comprehensive Profile Modal
    governmentIdSubmission: "Government ID",
    linksPortfolio: "Portfolio",
    workEligibility: "Eligibility",
    language: "Language",
    proficiency: "Proficiency",
    certification: "Certification",
    addLanguage: "Add Language",
    languageExample: "e.g., English, Arabic, French",
    selectProficiency: "Select proficiency level",
    basic: "Basic",
    conversational: "Conversational",
    fluent: "Fluent",
    native: "Native",
    certificationExample: "e.g., TOEFL, IELTS, DELF",
    technicalSkills: "Technical Skills",
    softSkills: "Soft Skills",
    addSkill: "Add Skill",
    skill: "Skill",
    technicalSkillExample: "e.g., JavaScript, React, Node.js",
    level: "Level",
    selectLevel: "Select level",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    expert: "Expert",
    yearsOfExperience: "Years of Experience",
    softSkillExample: "e.g., Communication, Leadership, Problem Solving",
    institution: "Institution",
    institutionPlaceholder: "e.g., University of Cairo",
    degree: "Degree",
    degreePlaceholder: "e.g., Bachelor of Science",
    fieldOfStudy: "Field of Study",
    fieldOfStudyPlaceholder: "e.g., Computer Science",
    location: "Location",
    locationPlaceholder: "e.g., Cairo, Egypt",
    startDate: "Start Date",
    endDate: "End Date",
    gpa: "GPA",
    gpaPlaceholder: "e.g., 3.8/4.0",
    currentlyStudyingHere: "Currently studying here",
    relevantCoursework: "Relevant Coursework",
    listRelevantCourses: "List relevant courses",
    addEducation: "Add Education",
    company: "Company",
    companyPlaceholder: "e.g., Google Inc.",
    position: "Position",
    positionPlaceholder: "e.g., Software Engineer",
    employmentType: "Employment Type",
    selectType: "Select type",
    fullTime: "Full-time",
    partTime: "Part-time",
    contract: "Contract",
    freelance: "Freelance",
    internship: "Internship",
    currentlyWorkingHere: "Currently working here",
    keyResponsibilitiesAchievements: "Responsibilities",
    describeKeyResponsibilitiesAchievements: "Describe your key responsibilities and achievements",
    addExperience: "Add Experience",
    certifications: "Certifications",
    addCertification: "Add Certification",
    certificationName: "Certification Name",
    certificationNamePlaceholder: "e.g., AWS Certified Developer",
    issuingOrganization: "Issuing Organization",
    issuingOrganizationPlaceholder: "e.g., Amazon Web Services",
    issueDate: "Issue Date",
    expiryDate: "Expiry Date",
    credentialId: "Credential ID",
    credentialIdPlaceholder: "e.g., CERT-123456",
    credentialUrl: "Credential URL",
    credentialUrlPlaceholder: "https://example.com/credential",
    certificateFile: "Certificate File",
    uploadCertificate: "Upload Certificate",
    awards: "Awards",
    addAward: "Add Award",
    awardTitle: "Award Title",
    awardTitlePlaceholder: "e.g., Employee of the Year",
    issuerPlaceholder: "e.g., Company Name",
    dateReceived: "Date Received",
    category: "Category",
    selectCategory: "Select category",
    academic: "Academic",
    professional: "Professional",
    community: "Community",
    sports: "Sports",
    artistic: "Artistic",
    description: "Description",
    describeAwardAchievement: "Describe this award or achievement",
    idType: "ID Type",
    selectIdType: "Select ID type",
    passport: "Passport",
    nationalId: "National ID",
    drivingLicense: "Driving License",
    idNumber: "ID Number",
    enterIdNumber: "Enter ID number",
    issuingAuthority: "Issuing Authority",
    enterIssuingAuthority: "Enter issuing authority",
    linkedinUrl: "LinkedIn URL",
    linkedinUrlPlaceholder: "https://linkedin.com/in/username",
    githubUrl: "GitHub URL",
    githubUrlPlaceholder: "https://github.com/username",
    portfolioUrl: "Portfolio URL",
    portfolioUrlPlaceholder: "https://yourportfolio.com",
    personalWebsite: "Personal Website",
    personalWebsitePlaceholder: "https://yourwebsite.com",
    behanceUrl: "Behance URL",
    behanceUrlPlaceholder: "https://behance.net/username",
    dribbbleUrl: "Dribbble URL",
    dribbbleUrlPlaceholder: "https://dribbble.com/username",
    workAuthorization: "Work Authorization",
    selectAuthorizationStatus: "Select authorization status",
    citizen: "Citizen",
    permanentResident: "Permanent Resident",
    workVisa: "Work Visa",
    studentVisa: "Student Visa",
    workArrangementPreference: "Work Arrangement Preference",
    selectPreference: "Select preference",
    onsite: "On-site",
    remote: "Remote",
    hybrid: "Hybrid",
    flexible: "Flexible",
    availabilityDate: "Availability Date",
    noticePeriod: "Notice Period",
    noticePeriodExample: "e.g., 2 weeks, 1 month",
    willingToRelocate: "Willing to Relocate",
    requireVisaSponsorship: "Require Visa Sponsorship",
    travelWillingness: "Travel Willingness",
    selectTravelWillingness: "Select travel willingness",
    none: "None",
    minimal: "Minimal",
    moderate: "Moderate",
    extensive: "Extensive",
    targetRoles: "Target Roles",
    targetIndustries: "Target Industries",
    targetCompanies: "Target Companies",
    careerLevel: "Career Level",
    selectCareerLevel: "Select career level",
    entryLevel: "Entry Level",
    junior: "Junior",
    midLevel: "Mid Level",
    senior: "Senior",
    lead: "Lead",
    manager: "Manager",
    director: "Director",
    executive: "Executive",
    salaryExpectations: "Salary Expectations",
    minimumSalary: "Minimum Salary",
    maximumSalary: "Maximum Salary",
    currency: "Currency",
    period: "Period",
    monthly: "Monthly",
    annually: "Annually",
    salaryIsNegotiable: "Salary is negotiable",
    careerGoals: "Career Goals",
    describeCareerGoalsAspirations: "Describe your career goals and aspirations",
    workStyle: "Work Style",
    describePreferredWorkStyle: "Describe your preferred work style",
    whatMotivatesYou: "What Motivates You",
    whatDrivesMotivatesCareer: "What drives and motivates you in your career?",
    dealBreakers: "Deal Breakers",
    dealBreakersJob: "What are your deal breakers in a job?",
    enterFirstName: "Enter first name",
    enterLastName: "Enter last name",
    enterEmail: "Enter email",
    enterPhone: "Enter phone number",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    selectGender: "Select gender",
    nationality: "Nationality",
    enterNationality: "Enter nationality",
    address: "Address",
    streetAddress: "Street Address",
    enterStreetAddress: "Enter street address",
    city: "City",
    enterCity: "Enter city",
    stateProvince: "State/Province",
    enterStateProvince: "Enter state or province",
    country: "Country",
    enterCountry: "Enter country",
    postalCode: "Postal Code",
    enterPostalCode: "Enter postal code",
    emergencyContact: "Emergency Contact",
    emergencyContactName: "Emergency contact name",
    relationshipToYou: "Relationship to you",
    emergencyContactPhone: "Emergency contact phone",
    name: "Name",
    relationship: "Relationship",
    saving: "Saving...",
    lastSaved: "Last saved",
    errorSavingProfile: "Error saving profile",
    pleaseCheckFieldsTryAgain: "Please check all required fields and try again.",
    saveError: "Save Error",
    saveErrorDescription: "There was an error saving your progress. Please try again.",
    saveDraft: "Save Draft",
    saveProgress: "Save Progress",
    enterZero: "0",
    egyptianPound: "EGP",
    usDollar: "USD",
    euro: "EUR",
    britishPound: "GBP",
    saudiRiyal: "SAR",
    uaeDirham: "AED",
    male: "Male",
    female: "Female",
    nonBinary: "Non-binary",
    preferNotToSay: "Prefer not to say",
    other: "Other",
    workExperience: "Work Experience",
    validEmailRequired: "Valid email is required",
    validPhoneNumberRequired: "Valid phone number is required",
    hourly: "Hourly",
    hourlyPlaceholder: "e.g., 50",
    skills: {
      industryKnowledge: "Industry Knowledge",
      tools: "Tools",
      addIndustryKnowledge: "Add Industry Knowledge",
      addTools: "Add Tools",
      industryKnowledgePlaceholder: "e.g., Finance, Healthcare, Technology",
      toolsPlaceholder: "e.g., Figma, Adobe Creative Suite, Jira",
    },
    industryKnowledge: "Industry Knowledge",
    tools: "Tools",
    addIndustryKnowledge: "Add Industry Knowledge",
    addTools: "Add Tools",
    industryKnowledgePlaceholder: "e.g., Finance, Healthcare, Technology",
    toolsPlaceholder: "e.g., Figma, Adobe Creative Suite, Jira",
    thesis: "Thesis",
    thesisPlaceholder: "e.g., 'Machine Learning Applications in Healthcare'",
    technologies: "Technologies",
    technologiesPlaceholder: "e.g., React, Node.js, Python",
    teamSize: "Team Size",
    teamSizePlaceholder: "e.g., 5-10",
    reportingTo: "Reporting To",
    reportingToPlaceholder: "e.g., Engineering Manager",
    salary: "Salary",
    salaryAmount: "Salary Amount",
    salaryAmountPlaceholder: "e.g., 5000",
    benefits: "Benefits",
    healthInsurance: "Health Insurance",
    retirementPlan: "Retirement Plan",
    paidTimeOff: "Paid Time Off",
    flexibleSchedule: "Flexible Schedule",
    remoteWork: "Remote Work",
    professionalDevelopment: "Professional Development",
    stockOptions: "Stock Options",
    otherBenefits: "Other Benefits",
    addOtherBenefit: "Add Other Benefit",
    otherBenefitPlaceholder: "e.g., Company Car, Gym Membership",
  },
  ar: {
    // Navigation & General
    welcome: "مرحباً بك في بلاتو!",
    buildProfile: "أنشئ ملفك الشخصي الكامل",
    takeInterview: "خذ مقابلة الذكاء الاصطناعي",
    getStarted: "ابدأ مع بلاتو",
    complete: "مكتمل",
    startInterview: "ابدأ المقابلة",
    buildProfileButton: "أنشئ الملف الشخصي",
    
    // Profile Section
    profileDescription: "أنشئ ملفك الشخصي المهني بما في ذلك التفاصيل الشخصية والتعليم وخبرة العمل والمهارات والتفضيلات المهنية. اوصل إلى 75% لفتح المقابلات.",
    interviewDescription: "أنشئ ملفك الشخصي إلى 75% من الاكتمال لفتح مقابلة الذكاء الاصطناعي.",
    
    // Steps
    step1: "أنشئ ملفك الشخصي الكامل بما في التفاصيل الشخصية والتعليم وخبرة العمل والمهارات والتفضيلات المهنية.",
    step2: "أكمل مقابلة الذكاء الاصطناعي لإنشاء تحليلك المهني الشامل.",
    
    // Common buttons
    save: "حفظ",
    cancel: "إلغاء",
    continue: "متابعة",
    next: "التالي",
    previous: "السابق",
    close: "إغلاق",
    signOut: "تسجيل الخروج",
    signingOut: "جاري تسجيل الخروج...",
    
    // Interview specific
    selectLanguage: "اختر لغة المقابلة",
    interviewLanguagePrompt: "بأي لغة تريد إجراء المقابلة؟",
    english: "English",
    arabic: "العربية",
    proceedInEnglish: "متابعة بالإنجليزية",
    proceedInArabic: "متابعة بالعربية",
    chooseStyle: "اختر أسلوب المقابلة",
    selectExperience: "المقابلة - اختر كيف تريد خوض تجربة مقابلة الذكاء الاصطناعي",
    languageNote: "سيطرح المحاور الذكي الأسئلة ويتوقع الإجابات باللغة التي اخترتها",
    
    // Interview Modal
    interview: {
      chooseStyle: "اختر أسلوب المقابلة",
      selectExperience: "اختر نوع المقابلة",
      selectLanguage: "اختر لغة المقابلة",
      languageNote: "سيطرح المحاور الذكي الأسئلة ويتوقع الإجابات باللغة التي اخترتها",
      // Error messages
      voiceInterviewError: "خطأ في المقابلة الصوتية",
      voiceInterviewErrorDescription: "حدثت مشكلة في المقابلة الصوتية. يرجى محاولة وضع النص بدلاً من ذلك.",
      unauthorized: "غير مصرح به",
      loggingOut: "لقد قمت بتسجيل الخروج. جاري تسجيل الدخول مرة أخرى...",
      startError: "خطأ",
      startErrorDescription: "فشل في بدء المقابلة. يرجى المحاولة مرة أخرى.",
      allInterviewsComplete: "اكتملت جميع المقابلات!",
      profileGeneratedSuccessfully: "تم إنشاء ملفك الشخصي الشامل بالذكاء الاصطناعي بنجاح.",
      interviewSectionComplete: "اكتملت قسم المقابلة",
      movingTo: "الانتقال إلى",
      interview: "مقابلة",
      continueRemainingInterviews: "تابع مع المقابلات المتبقية لإكمال ملفك الشخصي.",
      processResponseError: "خطأ",
      processResponseErrorDescription: "فشل في معالجة ردك",
      submissionFailed: "فشل التقديم",
      submissionFailedDescription: "حدثت مشكلة في تقديم مقابلتك. يرجى المحاولة مرة أخرى.",
      voiceInterviewComplete: "اكتملت المقابلة الصوتية!",
      voiceInterviewProcessedSuccessfully: "تمت معالجة مقابلتك الصوتية بنجاح.",
      processingFailed: "فشل المعالجة",
      processingFailedDescription: "حدثت مشكلة في معالجة مقابلتك",
      processAnswerError: "خطأ",
      processAnswerErrorDescription: "فشل في معالجة إجابتك. يرجى المحاولة مرة أخرى.",
      completeInterviewError: "خطأ",
      completeInterviewErrorDescription: "فشل في إكمال المقابلة. يرجى المحاولة مرة أخرى.",
      selectInterviewTypeError: "خطأ",
      selectInterviewTypeErrorDescription: "يرجى تحديد نوع المقابلة أولاً.",
      startingVoiceInterviewConnecting: "جاري بدء مقابلتك الصوتية... الاتصال بمحاور الذكاء الاصطناعي...",
      voiceInterviewStarted: "بدأت المقابلة الصوتية",
      voiceInterviewStartedDescription: "يمكنك الآن التحدث بطبيعية مع محاور الذكاء الاصطناعي.",
      connectionFailed: "فشل الاتصال",
      couldNotStartVoiceInterview: "لم يتمكن من بدء المقابلة الصوتية",
      tryTextMode: "يرجى محاولة وضع النص",
      startingTextInterview: "جاري بدء مقابلتك النصية... يرجى الانتظار بينما أعد أسئلتك المخصصة.",
      questionContentNotAvailable: "محتوى السؤال غير متاح",
      textInterviewStarted: "بدأت المقابلة النصية",
      textInterviewStartedDescription: "يمكنك الآن كتابة ردودك على أسئلة المقابلة.",
      failedToStartInterview: "فشل في بدء المقابلة",
      couldNotStartTextInterview: "لم يتمكن من بدء المقابلة النصية",
      pleaseTryAgain: "يرجى المحاولة مرة أخرى",
      question1: "السؤال 1",
      interviewInProgress: "المقابلة قيد التقدم",
      waitBeforeClosing: "يرجى الانتظار حتى اكتمال التفاعل الحالي قبل الإغلاق.",
      chooseYourInterview: "اختر مقابلتك",
      completeAllInterviews: "أكمل جميع 3 مقابلات لإنشاء ملفك الشخصي الشامل بالذكاء الاصطناعي",
      interviewOrder: "يجب إكمال المقابلات بهذا الترتيب: الشخصية → المهنية → التقنية",
      locked: "(مقفلة)",
      completePreviousInterviews: "أكمل المقابلات السابقة أولاً",
      completed: "مكتمل",
      start: "ابدأ",
      backToInterviewTypes: "← العودة إلى أنواع المقابلات",
      preparingInterviewQuestions: "جاري إعداد أسئلة المقابلة...",
      typeResponsesAtOwnPace: "اكتب ردودك على وتيرتك الخاصة",
      textInterview: "مقابلة نصية",
      preparingQuestions: "جاري إعداد الأسئلة...",
      processingYourResponse: "جاري معالجة ردك...",
      interviewComplete: "اكتملت المقابلة!",
      interviewSectionCompletedSuccessfully: "اكتمل قسم المقابلة بنجاح! تابع مع المقابلات المتبقية لإكمال ملفك الشخصي.",
      typeYourAnswerHere: "اكتب إجابتك هنا...",
      submitting: "جاري التقديم...",
      submitInterview: "تقديم المقابلة",
      processing: "جاري المعالجة...",
      submitAnswer: "تقديم الإجابة",
      live: "مباشر",
      startingInterview: "جاري بدء المقابلة...",
      aiIsSpeaking: "الذكاء الاصطناعي يتحدث...",
      aiInterviewActive: "المقابلة مع الذكاء الاصطناعي نشطة",
      connecting: "جاري الاتصال...",
      preparingYourPersonalizedQuestions: "جاري إعداد أسئلتك المخصصة...",
      waitForAiToFinishSpeaking: "يرجى الانتظار حتى ينتهي الذكاء الاصطناعي من التحدث قبل الرد",
      aiWillGuideYou: "سيرشدك الذكاء الاصطناعي خلال",
      questions: "أسئلة",
      settingUpVoiceInterview: "إعداد مقابلتك الصوتية...",
      aiInterviewer: "محاور الذكاء الاصطناعي",
      you: "أنت",
      processingInterview: "جاري معالجة المقابلة...",
      hangUp: "إنهاء الاتصال",
      aiInterview: "مقابلة الذكاء الاصطناعي",
      success: "نجاح",
      resumeUploadedSuccessfully: "تم رفع السيرة الذاتية بنجاح! يمكنك الآن بدء المقابلات."
    },
    
    // Interview Types
    voiceInterview: "مقابلة صوتية",
    textInterview: "مقابلة نصية",
    startingVoiceInterview: "بدء المقابلة الصوتية...",
    speakNaturally: "تحدث بطبيعية مع المحاور الذكي",
    
    // Interview type descriptions
    personalInterview: "مقابلة شخصية",
    personalInterviewDescription: "فهمك الشخصي، وخلفيتك، وتاريخك",
    professionalInterview: "مقابلة مهنية",
    professionalInterviewDescription: "استكشاف خلفيتك المهنية وخبرتك العملية",
    technicalInterview: "مقابلة تقنية",
    technicalInterviewDescription: "تقييم ديناميكي يعتمد على مجالك - حل المشكلات وتقييم الذكاء",
    
    // Languages
    languages: {
      english: "English",
      arabic: "العربية"
    },
    
    // Brand name
    plato: "بلاتو",
    
    // Profile completion
    profileProgress: "تم حفظ تقدم الملف الشخصي!",
    profileComplete: "ملفك الشخصي مكتمل بنسبة {{percentage}}%. {{status}}",
    interviewsUnlocked: "رائع! ملفك الشخصي جاهز للمقابلات (مكتمل 75%+).",
    continueBuilding: "تابع البناء لفتح المقابلات عند 75%.",
    
    // Dashboard
    jobDashboard: "لوحة الوظائف الخاصة بك",
    
    // Dashboard sections
    jobMatches: "الوظائف المناسبة",
    applications: "الطلبات",
    upcomingInterviews: "المقابلات القادمة",
    jobPostings: "الوظائف المتاحة",
    
    // Dashboard content
    aiCuratedOpportunities: "الفرص المختارة بالذكاء الاصطناعي",
    discoverPersonalizedJobs: "اكتشف الوظائف المخصصة لك بناءً على تحليل مقابلة الذكاء الاصطناعي وبيانات ملفك الشخصي",
    trackApplicationProgress: "تتبع تقدم الطلبات",
    monitorApplicationStatus: "راقب طلبات العمل ومواعيد المقابلات عبر جميع المنصات",
    exploreOpportunities: "استكشف الفرص الجديدة",
    browseLatestJobs: "تصفح أحدث الوظائف المتاحة التي تناسب مهاراتك وأهدافك المهنية",
    viewUpcomingSchedule: "اعرض جدولك القادم",
    stayUpdated: "ابق محدثاً بمقابلاتك المؤكدة والتواريخ المهمة",
    
    // Stats and labels
    responseRate: "معدل الرد",
    applicationResponseRate: "معدل الرد على الطلبات",
    whyJobSeekingChallenging: "لماذا البحث عن عمل صعب للغاية؟",
    
    // Common actions
    viewAll: "عرض الكل",
    noDataAvailable: "لا توجد بيانات متاحة",
    loadingData: "جاري تحميل البيانات...",
    
    // Applications section
    myApplications: "طلباتي",
    trackApplicationStatus: "تتبع حالة وتقدم طلباتك",
    
    // Quick stats
    quickStats: "إحصائيات سريعة",
    jobMatchesLabel: "الوظائف المناسبة",
    applicationsLabel: "الطلبات",
    profileCompletionLabel: "اكتمال الملف",
    
    // Industry challenge stats
    avgJobSearchTime: "متوسط وقت البحث عن عمل",
    applicationsToGetOffer: "طلب للحصول على عرض واحد",
    sixMonths: "٦ أشهر",
    oneHundredEighteen: "١١٨",
    twoPercent: "٢٪",
    
    // Forms
    personalDetails: "التفاصيل الشخصية",
    workExperience: "خبرة العمل",
    education: "التعليم",
    skills: "المهارات",
    jobTarget: "الهدف الوظيفي",
    
    // Language switch
    switchLanguage: "English",
    
    // Landing page
    landing: {
      hero: {
        title: "اعثر على وظيفة أحلامك بدقة الذكاء الاصطناعي",
        subtitle: "حوّل رحلتك المهنية مع المطابقة الذكية للوظائف ومقابلات الذكاء الاصطناعي الشاملة التي تُظهر إمكاناتك الحقيقية.",
        getStarted: "ابدأ الآن",
        learnMore: "اعرف المزيد"
      },
      features: {
        aiPoweredMatching: "المطابقة بالذكاء الاصطناعي",
        smartInterviews: "مقابلات ذكية",
        instantResults: "نتائج فورية",
        aiInterview: {
          title: "مقابلة الذكاء الاصطناعي",
          description: "أجرِ محادثة طبيعية مع الذكاء الاصطناعي لبناء ملفك المهني تلقائياً"
        },
        smartMatching: {
          title: "المطابقة الذكية", 
          description: "احصل على وظائف مطابقة بدقة مع تقييم شامل يعتمد على مهاراتك وخبرتك وأهدافك"
        },
        instantResultsFeature: {
          title: "نتائج فورية",
          description: "اطلع على مطابقاتك فوراً مع تقييم مفصل وتتبع للطلبات"
        }
      },
      companies: {
        title: "موثوق من قبل الشركات الرائدة",
        subtitle: "انضم إلى آلاف المحترفين الذين وجدوا المطابقة المهنية المثالية من خلال منصتنا المدعومة بالذكاء الاصطناعي",
        testimonial: "نهج ثوري في اكتساب المواهب",
        subtitle2: "انضم إلى الشركات التي تشكل مستقبل التوظيف"
      },
      cta: {
        title: "هل أنت مستعد للعثور على وظيفتك المثالية؟",
        subtitle: "انضم إلى آلاف المحترفين الذين اكتشفوا وظائف أحلامهم بمطابقة الذكاء الاصطناعي",
        startJourney: "ابدأ رحلتك"
      }
    },
    
    // Auth
    auth: {
      signIn: "تسجيل الدخول",
      signUp: "إنشاء حساب",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      username: "اسم المستخدم",
      enterEmail: "أدخل بريدك الإلكتروني",
      enterPassword: "أدخل كلمة المرور",
      confirmYourPassword: "أكد كلمة المرور",
      firstNamePlaceholder: "الاسم الأول",
      lastNamePlaceholder: "اسم العائلة",
      usernamePlaceholder: "اسم المستخدم",
      usernameOptional: "اسم المستخدم (اختياري)",
      chooseUsername: "اختر اسم المستخدم",
      createPassword: "أنشئ كلمة مرور",
      signingIn: "جاري تسجيل الدخول...",
      signingUp: "جاري إنشاء الحساب...",
      createAccount: "إنشاء حساب",
      invalidEmail: "عنوان بريد إلكتروني غير صحيح",
      passwordRequired: "كلمة المرور مطلوبة",
      passwordMinLength: "يجب أن تكون كلمة المرور ٦ أحرف على الأقل",
      firstNameRequired: "الاسم الأول مطلوب",
      lastNameRequired: "اسم العائلة مطلوب",
      usernameMinLength: "يجب أن يكون اسم المستخدم ٣ أحرف على الأقل",
      passwordsDontMatch: "كلمات المرور غير متطابقة",
      welcomeToPlato: "أهلاً بك في بلاتو"
    },
    
    // Dashboard
    dashboard: {
      invalidFileType: "نوع ملف غير صالح",
      invalidFileTypeDescription: "يرجى رفع ملف PDF أو نصي.",
      pdfUploadTips: "نصائح رفع PDF",
      pdfUploadTipsDescription: "تم رفع PDF! للحصول على التعبئة التلقائية التامة، جرب أيضاً رفع نسخة نصية (.txt) من سيرتك الذاتية إذا لم يعمل استخراج PDF بشكل جيد.",
      fileTooLarge: "ملف كبير جداً",
      fileTooLargeDescription: "يرجى رفع ملف أصغر من 10 ميجابايت.",
      resumeProcessedSuccessfully: "تم معالجة السيرة الذاتية بنجاح! 🎉",
      resumeProcessedDescription: "تم ملء الملف الشخصي تلقائياً بـ {{sections}} من أقسام سيرتك الذاتية.",
      uploadFailed: "فشل الرفع",
      uploadFailedDescription: "فشل معالجة السيرة الذاتية. يرجى المحاولة مرة أخرى.",
      editingProfile: "جاري تعديل الملف الشخصي...",
      readyToFindRole: "جاري البحث عن دورك المثالي! 🎉",
      readyToFindRoleDescription: "ملفك الشخصي مكتمل ومقابلة الذكاء الاصطناعي قد أنشأت تحليلاً مهنياً شاملاً. استخدم الأدوات أدناه لاكتشاف الفرص التي تتوافق مع مهاراتك وأهدافك المهنية الفريدة.",
      completeSteps: "أكمل الخطوتين التاليتين لفتح المطابقة الوظيفية المخصصة والوصول إلى لوحة التحكم الكاملة:",
      uploadResume: "رفع السيرة الذاتية",
      uploading: "جاري الرفع...",
      editProfile: "تعديل الملف الشخصي",
      excellentInterviewComplete: "ممتاز! مقابلة الذكاء الاصطناعي مكتملة.",
      reviewInterview: "مراجعة المقابلة",
      jobSpecificAI: "مقابلات الذكاء الاصطناعي الخاصة بالوظائف",
      jobSpecificAIDescription: "شاهد دعوات وظيفية مخصصة لك وتمرن عليها",
      invitedJobs: "الوظائف المدعوة إليها",
      invitedJobsDescription: "شاهد الوظائف التي تمت دعوتك إليها وتقدم لها",
      browseJobPostings: "تصفح الوظائف المعلنة",
      getStartedWithPlato: "ابدأ مع بلاتو",
      getStartedWithPlatoDescription: "أكمل الخطوتين أعلاه لفتح لوحة تحكم وظيفية مخصصة مع المطابقات والطلبات والرؤى المهنية.",
      step1Description: "الخطوة 1: أنشئ ملفك الشخصي الكامل بما في التفاصيل الشخصية والتعليم وخبرة العمل والمهارات والتفضيلات المهنية.",
      step2Description: "الخطوة 2: أكمل مقابلة الذكاء الاصطناعي لإنشاء تحليلك المهني الشامل.",
      
      // Additional missing translations
      phone: "هاتف",
      selectGender: "اختر الجنس",
      selectCareerLevel: "اختر مستوى المهنة",
      entryLevel: "مستوى الدخول",
      junior: "مبتدئ",
      midLevel: "متوسط",
      senior: "رائد",
      lead: "قائد",
      manager: "مدير",
      director: "مدير تنفيذي",
      executive: "تنفيذي",
      selectType: "اختر النوع",
      fullTime: "دوام كامل",
      partTime: "دوام جزئي",
      contract: "عقد",
      freelance: "حر",
      internship: "تدريب",
      selectAuthorizationStatus: "اختر حالة التصريح",
      citizen: "مواطن",
      permanentResident: "مقيم دائم",
      workVisa: "فيزا عمل",
      studentVisa: "فيزا طالب",
      selectPreference: "اختر التفضيل",
      onsite: "في الموقع",
      remote: "عن بعد",
      hybrid: "هجين",
      flexible: "مرن",
      selectTravelWillingness: "اختر استعداد السفر",
      none: "لا شيء",
      minimal: "محدود",
      moderate: "متوسط",
      extensive: "شامل",
      targetRoles: "الأدوار المستهدفة",
      targetIndustries: "الصناعات المستهدفة",
      targetCompanies: "الشركات المستهدفة",
      salaryExpectations: "توقعات الراتب",
      minimumSalary: "الحد الأدنى للراتب",
      maximumSalary: "الحد الأقصى للراتب",
      currency: "العملة",
      period: "الفترة",
      monthly: "شهرياً",
      annually: "سنوياً",
      salaryIsNegotiable: "الراتب قابل للتفاوض",
      careerGoals: "أهداف المهنة",
      describeCareerGoalsAspirations: "صف أهدافك وأمانيك المهنية",
      workStyle: "أسلوب العمل",
      describePreferredWorkStyle: "صف أسلوب العمل المفضل لديك",
      whatMotivatesYou: "ما الذي يلهمك؟",
      whatDrivesMotivatesCareer: "ما الذي يدفع ويحفزك في مسيرتك المهنية؟",
      dealBreakers: "العوائق",
      dealBreakersJob: "ما هي عوائقك في وظيفة؟",
      enterFirstName: "أدخل الاسم الأول",
      enterLastName: "أدخل اسم العائلة",
      enterEmail: "أدخل البريد الإلكتروني",
      enterPhone: "أدخل رقم الهاتف",
      dateOfBirth: "تاريخ الميلاد",
      gender: "الجنس",
      nationality: "الجنسية",
      enterNationality: "أدخل الجنسية",
      address: "العنوان",
      streetAddress: "عنوان الشارع",
      enterStreetAddress: "أدخل عنوان الشارع",
      city: "المدينة",
      enterCity: "أدخل المدينة",
      stateProvince: "الولاية/المحافظة",
      enterStateProvince: "أدخل الولاية أو المحافظة",
      country: "الدولة",
      enterCountry: "أدخل الدولة",
      postalCode: "الرمز البريدي",
      enterPostalCode: "أدخل الرمز البريدي",
      emergencyContact: "جهة الاتصال في حالات الطوارئ",
      emergencyContactName: "اسم جهة الاتصال في حالات الطوارئ",
      relationshipToYou: "علاقتك به",
      emergencyContactPhone: "هاتف جهة الاتصال في حالات الطوارئ",
      name: "الاسم",
      relationship: "العلاقة",
      saving: "جاري الحفظ...",
      lastSaved: "آخر حفظ",
      errorSavingProfile: "خطأ في حفظ الملف الشخصي",
      pleaseCheckFieldsTryAgain: "يرجى التحقق من جميع الحقول المطلوبة والمحاولة مرة أخرى.",
      saveError: "خطأ في الحفظ",
      saveErrorDescription: "حدث خطأ أثناء حفظ تقدمك. يرجى المحاولة مرة أخرى.",
      saveDraft: "حفظ المسودة",
      saveProgress: "حفظ التقدم",
      enterZero: "0",
      egyptianPound: "ج.م",
      usDollar: "دولار أمريكي",
      euro: "يورو",
      britishPound: "جنيه إسترليني",
      saudiRiyal: "ريال سعودي",
      uaeDirham: "درهم إماراتي",
      male: "ذكر",
      female: "أنثى",
      nonBinary: "غير ثنائي",
      preferNotToSay: "أفضل عدم الإفصاح",
      other: "آخر",
      validEmailRequired: "البريد الإلكتروني الصالح مطلوب",
      validPhoneNumberRequired: "رقم الهاتف الصالح مطلوب",
      hourly: "بالساعة",
      hourlyPlaceholder: "مثال: 50",
      skills: {
        industryKnowledge: "المعرفة الصناعية",
        tools: "الأدوات",
        addIndustryKnowledge: "إضافة معرفة صناعية",
        addTools: "إضافة أدوات",
        industryKnowledgePlaceholder: "مثال: المالية، الرعاية الصحية، التكنولوجيا",
        toolsPlaceholder: "مثال: Figma، Adobe Creative Suite، Jira",
      },
      industryKnowledge: "المعرفة الصناعية",
      tools: "الأدوات",
      addIndustryKnowledge: "إضافة معرفة صناعية",
      addTools: "إضافة أدوات",
      industryKnowledgePlaceholder: "مثال: المالية، الرعاية الصحية، التكنولوجيا",
      toolsPlaceholder: "مثال: Figma، Adobe Creative Suite، Jira",
      thesis: "الأطروحة",
      thesisPlaceholder: "مثال: 'تطبيقات التعلم الآلي في الرعاية الصحية'",
      technologies: "التقنيات",
      technologiesPlaceholder: "مثال: React، Node.js، Python",
      teamSize: "حجم الفريق",
      teamSizePlaceholder: "مثال: 5-10",
      reportingTo: "الإبلاغ إلى",
      reportingToPlaceholder: "مثال: مدير الهندسة",
      salary: "الراتب",
      salaryAmount: "مبلغ الراتب",
      salaryAmountPlaceholder: "مثال: 5000",
      benefits: "المزايا",
      healthInsurance: "تأمين صحي",
      retirementPlan: "خطة تقاعد",
      paidTimeOff: "إجازة مدفوعة الأجر",
      flexibleSchedule: "جدول مرن",
      remoteWork: "عمل عن بعد",
      professionalDevelopment: "التطوير المهني",
      stockOptions: "خيارات الأسهم",
      otherBenefits: "مزايا أخرى",
      addOtherBenefit: "إضافة ميزة أخرى",
      otherBenefitPlaceholder: "مثال: سيارة الشركة، عضوية نادي رياضي",
    },
    
    // Comprehensive Profile Modal
    governmentIdSubmission: "تقديم الهوية الحكومية",
    linksPortfolio: "الروابط والمعرض",
    workEligibility: "الصلاحية والتفضيلات العملية",
    language: "اللغة",
    proficiency: "المستوى",
    certification: "الشهادة",
    addLanguage: "إضافة لغة",
    languageExample: "مثال: الإنجليزية، العربية، الفرنسية",
    selectProficiency: "اختر مستوى الكفاءة",
    basic: "مبتدئ",
    conversational: "محادثة",
    fluent: "تقليدية",
    native: "الأم",
    certificationExample: "مثال: TOEFL, IELTS, DELF",
    technicalSkills: "المهارات التقنية",
    softSkills: "المهارات الناعمة",
    addSkill: "إضافة مهارة",
    skill: "المهارة",
    technicalSkillExample: "مثال: JavaScript, React, Node.js",
    level: "المستوى",
    selectLevel: "اختر المستوى",
    beginner: "مبتدئ",
    intermediate: "متوسط",
    advanced: "متقدم",
    expert: "خبير",
    yearsOfExperience: "سنوات الخبرة",
    softSkillExample: "مثال: التواصل، القيادة، حل المشكلات",
    institution: "المؤسسة",
    institutionPlaceholder: "مثال: جامعة القاهرة",
    degree: "الدرجة",
    degreePlaceholder: "مثال: بكالوريوس العلوم",
    fieldOfStudy: "تخصص الدراسة",
    fieldOfStudyPlaceholder: "مثال: علوم الحاسب",
    location: "الموقع",
    locationPlaceholder: "مثال: القاهرة، مصر",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    gpa: "المعدل التراكمي",
    gpaPlaceholder: "مثال: 3.8/4.0",
    currentlyStudyingHere: "أدرس حالياً هنا",
    relevantCoursework: "المقررات ذات الصلة",
    listRelevantCourses: "سرد المقررات ذات الصلة",
    addEducation: "إضافة تعليم",
    company: "الشركة",
    companyPlaceholder: "مثال: جوجل",
    position: "المنصب",
    positionPlaceholder: "مثال: مهندس برمجيات",
    employmentType: "نوع التوظيف",
    selectType: "اختر النوع",
    fullTime: "دوام كامل",
    partTime: "دوام جزئي",
    contract: "عقد",
    freelance: "حر",
    internship: "تدريب",
    currentlyWorkingHere: "أعمل حالياً هنا",
    keyResponsibilitiesAchievements: "المسؤوليات الرئيسية والإنجازات",
    describeKeyResponsibilitiesAchievements: "صف مسؤولياتك الرئيسية والإنجازات",
    addExperience: "إضافة خبرة",
    certifications: "الشهادات والتراخيص",
    addCertification: "إضافة شهادة",
    certificationName: "اسم الشهادة",
    certificationNamePlaceholder: "مثال: مطور AWS المعتمد",
    issuingOrganization: "الجهة المانحة",
    issuingOrganizationPlaceholder: "مثال: خدمات أمازون ويب",
    issueDate: "تاريخ الإصدار",
    expiryDate: "تاريخ الانتهاء",
    credentialId: "معرّف الشهادة",
    credentialIdPlaceholder: "مثال: CERT-123456",
    credentialUrl: "رابط الشهادة",
    credentialUrlPlaceholder: "https://example.com/credential",
    certificateFile: "ملف الشهادة",
    uploadCertificate: "رفع الشهادة",
    awards: "الجوائز والإنجازات",
    addAward: "إضافة جائزة",
    awardTitle: "اسم الجائزة",
    awardTitlePlaceholder: "مثال: موظف العام",
    issuerPlaceholder: "مثال: اسم الشركة",
    dateReceived: "تاريخ الاستلام",
    category: "الفئة",
    selectCategory: "اختر الفئة",
    academic: "أكاديمي",
    professional: "مهني",
    community: "مجتمعي",
    sports: "رياضي",
    artistic: "فني",
    description: "الوصف",
    describeAwardAchievement: "صف هذه الجائزة أو الإنجاز",
    idType: "نوع الهوية",
    selectIdType: "اختر نوع الهوية",
    passport: "جواز السفر",
    nationalId: "الهوية الوطنية",
    drivingLicense: "رخصة القيادة",
    idNumber: "رقم الهوية",
    enterIdNumber: "أدخل رقم الهوية",
    issuingAuthority: "الجهة المانحة",
    enterIssuingAuthority: "أدخل الجهة المانحة",
    linkedinUrl: "رابط LinkedIn",
    linkedinUrlPlaceholder: "https://linkedin.com/in/username",
    githubUrl: "رابط GitHub",
    githubUrlPlaceholder: "https://github.com/username",
    portfolioUrl: "رابط المعرض",
    portfolioUrlPlaceholder: "https://yourportfolio.com",
    personalWebsite: "الموقع الشخصي",
    personalWebsitePlaceholder: "https://yourwebsite.com",
    behanceUrl: "رابط Behance",
    behanceUrlPlaceholder: "https://behance.net/username",
    dribbbleUrl: "رابط Dribbble",
    dribbbleUrlPlaceholder: "https://dribbble.com/username",
    workAuthorization: "التصريح العمل",
    selectAuthorizationStatus: "اختر حالة التصريح",
    citizen: "مواطن",
    permanentResident: "مقيم دائم",
    workVisa: "فيزا عمل",
    studentVisa: "فيزا طالب",
    workArrangementPreference: "تفضيل ترتيب العمل",
    selectPreference: "اختر التفضيل",
    onsite: "في الموقع",
    remote: "عن بعد",
    hybrid: "هجين",
    flexible: "مرن",
    availabilityDate: "تاريخ التوفر",
    noticePeriod: "فترة الإشعار",
    noticePeriodExample: "مثال: أسبوعان، شهر",
    willingToRelocate: "على استعداد للانتقال",
    requireVisaSponsorship: "يتطلب رعاية فيزا",
    travelWillingness: "استعداد السفر",
    selectTravelWillingness: "اختر استعداد السفر",
    targetRoles: "الأدوار المستهدفة",
    targetIndustries: "الصناعات المستهدفة",
    targetCompanies: "الشركات المستهدفة",
    careerLevel: "مستوى المهنة",
    selectCareerLevel: "اختر مستوى المهنة",
    entryLevel: "مستوى الدخول",
    junior: "مبتدئ",
    midLevel: "متوسط",
    senior: "رائد",
    lead: "قائد",
    manager: "مدير",
    director: "مدير تنفيذي",
    executive: "تنفيذي",
    salaryExpectations: "توقعات الراتب",
    minimumSalary: "الحد الأدنى للراتب",
    maximumSalary: "الحد الأقصى للراتب",
    currency: "العملة",
    period: "الفترة",
    monthly: "شهرياً",
    annually: "سنوياً",
    salaryIsNegotiable: "الراتب قابل للتفاوض",
    careerGoals: "أهداف المهنة",
    describeCareerGoalsAspirations: "صف أهدافك وأمانيك المهنية",
    workStyle: "أسلوب العمل",
    describePreferredWorkStyle: "صف أسلوب العمل المفضل لديك",
    whatMotivatesYou: "ما الذي يلهمك؟",
    whatDrivesMotivatesCareer: "ما الذي يدفع ويحفزك في مسيرتك المهنية؟",
    dealBreakers: "العوائق",
    dealBreakersJob: "ما هي عوائقك في وظيفة؟",
    enterFirstName: "أدخل الاسم الأول",
    enterLastName: "أدخل اسم العائلة",
    enterEmail: "أدخل البريد الإلكتروني",
    enterPhone: "أدخل رقم الهاتف",
    dateOfBirth: "تاريخ الميلاد",
    gender: "الجنس",
    nationality: "الجنسية",
    enterNationality: "أدخل الجنسية",
    address: "العنوان",
    streetAddress: "عنوان الشارع",
    enterStreetAddress: "أدخل عنوان الشارع",
    city: "المدينة",
    enterCity: "أدخل المدينة",
    stateProvince: "الولاية/المحافظة",
    enterStateProvince: "أدخل الولاية أو المحافظة",
    country: "الدولة",
    enterCountry: "أدخل الدولة",
    postalCode: "الرمز البريدي",
    enterPostalCode: "أدخل الرمز البريدي",
    emergencyContact: "جهة الاتصال في حالات الطوارئ",
    emergencyContactName: "اسم جهة الاتصال في حالات الطوارئ",
    relationshipToYou: "علاقتك به",
    emergencyContactPhone: "هاتف جهة الاتصال في حالات الطوارئ",
    name: "الاسم",
    relationship: "العلاقة",
    saving: "جاري الحفظ...",
    lastSaved: "آخر حفظ",
    errorSavingProfile: "خطأ في حفظ الملف الشخصي",
    pleaseCheckFieldsTryAgain: "يرجى التحقق من جميع الحقول المطلوبة والمحاولة مرة أخرى.",
    saveError: "خطأ في الحفظ",
    saveErrorDescription: "حدث خطأ أثناء حفظ تقدمك. يرجى المحاولة مرة أخرى.",
    saveDraft: "حفظ المسودة",
    saveProgress: "حفظ التقدم",
    enterZero: "0",
    egyptianPound: "ج.م",
    usDollar: "دولار أمريكي",
    euro: "يورو",
    britishPound: "جنيه إسترليني",
    saudiRiyal: "ريال سعودي",
    uaeDirham: "درهم إماراتي",
    male: "ذكر",
    female: "أنثى",
    nonBinary: "غير ثنائي",
    preferNotToSay: "أفضل عدم الإفصاح",
    other: "آخر",
    workExperience: "خبرة العمل",
    validEmailRequired: "البريد الإلكتروني الصالح مطلوب",
    validPhoneNumberRequired: "رقم الهاتف الصالح مطلوب",
    hourly: "بالساعة",
    hourlyPlaceholder: "مثال: 50",
    skills: {
      industryKnowledge: "المعرفة الصناعية",
      tools: "الأدوات",
      addIndustryKnowledge: "إضافة معرفة صناعية",
      addTools: "إضافة أدوات",
      industryKnowledgePlaceholder: "مثال: المالية، الرعاية الصحية، التكنولوجيا",
      toolsPlaceholder: "مثال: Figma، Adobe Creative Suite، Jira",
    },
    industryKnowledge: "المعرفة الصناعية",
    tools: "الأدوات",
    addIndustryKnowledge: "إضافة معرفة صناعية",
    addTools: "إضافة أدوات",
    industryKnowledgePlaceholder: "مثال: المالية، الرعاية الصحية، التكنولوجيا",
    toolsPlaceholder: "مثال: Figma، Adobe Creative Suite، Jira",
    thesis: "الأطروحة",
    thesisPlaceholder: "مثال: 'تطبيقات التعلم الآلي في الرعاية الصحية'",
    technologies: "التقنيات",
    technologiesPlaceholder: "مثال: React، Node.js، Python",
    teamSize: "حجم الفريق",
    teamSizePlaceholder: "مثال: 5-10",
    reportingTo: "الإبلاغ إلى",
    reportingToPlaceholder: "مثال: مدير الهندسة",
    salary: "الراتب",
    salaryAmount: "مبلغ الراتب",
    salaryAmountPlaceholder: "مثال: 5000",
    benefits: "المزايا",
    healthInsurance: "تأمين صحي",
    retirementPlan: "خطة تقاعد",
    paidTimeOff: "إجازة مدفوعة الأجر",
    flexibleSchedule: "جدول مرن",
    remoteWork: "عمل عن بعد",
    professionalDevelopment: "التطوير المهني",
    stockOptions: "خيارات الأسهم",
    otherBenefits: "مزايا أخرى",
    addOtherBenefit: "إضافة ميزة أخرى",
    otherBenefitPlaceholder: "مثال: سيارة الشركة، عضوية نادي رياضي",
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('plato-language');
    return (saved as Language) || 'en';
  });

  const isRTL = language === 'ar';

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('plato-language', lang);
    
    // Update document direction and language
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let translation: any = translations[language];
    
    for (const k of keys) {
      if (translation && typeof translation === 'object' && k in translation) {
        translation = translation[k];
      } else {
        return key; // Return the key if translation not found
      }
    }
    
    return typeof translation === 'string' ? translation : key;
  };

  // Set initial direction and language on mount
  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}